### ISSUE TITLE
Review phpcs & phpdocs fixing all warnings and errors there

### ISSUE THREAD

**Issue by stronk7** [moodlehq/moodle-local_chatlogs#13]
While moving this repo from Travis to GHA (see #14), it has been detected that:
- The phpcs test returns a good number of warnings that should be fixed. Once done, we can enable `--max-warnings 0` in the test.
- The phpdoc test has been disabled completely. There are a bunch of missing docs here and there.

Ciao :-)

**Comment by mudrd8mz** [comment]
Out of topic, we recently had a discussion within the team whether it is still reasonable and worth keeping this plugin alive. As it turned out https://moodle.org/local/chatlogs/ does not have any chats recorded since February and noone really noticed. There are zillions of narrow focused dedicated chat rooms created on various channels / platforms and this archive became interesting for spammers only ...

**Comment by stronk7** [comment]
Well, it has been asked/commented a couple of times along the last year @ dev chat.

Note: We have ALL the chat logs since last year being saved by Kevin bot (that includes everything ever posted into the matrix room plus everything coming from the Telegram-Matrix room sync). Just in case we want to switch and fetch from there.

I remember that I asked about that when creating matrixbot (really quickly, before starting to lose messages, in fact I think it was the very first feature implemented) about to apply for the switch. But I don't remember if that was just some informal discussion with you, somebody else... or what.

In any case, whatever you decide, 100%. I only can say that the logs are available, it's just a matter of apply for the switch (there may be slight formatting differences, from memory) and done. I remember I did the entry entry point to be highly similar to the telegrambot one. But... up to you!

Ciao :-)
